# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run autopep8 to format the code
    - name: Run autopep8
      run: |
        pip install autopep8
        autopep8 --in-place --recursive .

    # Run Pyflakes for static analysis
    - name: Run Pyflakes
      run: |
        pip install pyflakes
        pyflakes ./hw2_debugging.py  ./rand.py

    # Run Pylint for code linting
    - name: Run Pylint
      run: |
        pip install pylint
        pylint ./hw2_debugging.py  ./rand.py # Add other files as needed

    # Run tests with pytest and collect coverage
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest testFile.py testFile_hw2.py --doctest-modules --junitxml=junit/test-results.xml --cov=./src --cov-report=xml --cov-report=html
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
